### ISSUE TITLE
Create /data/data/com.termux/files/usr/bin/applets before curling, One-line if statement in line 46 doesn't work.

### ISSUE THREAD

**Issue by ghost** [MrAlpha786/termux-login-password#2]
Besides the issues, I really like the lock, because unlike others.( Atleast on the top search results. ) They only work on bash ( I meant the default shell, not what script they are running on. My default shell is zsh ). And they require python and other dependencies which waste storage space.

**Comment by MrAlpha786** [comment]
Thanks for letting me know.

I think, the new termux bootstrap don't contain applets directory. Adding a simple condition will fix this.

**Comment by MrAlpha786** [comment]
fixed🙂
